/*
Copyright 2016 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.
/**
 * Welcome to your Workbox-powered service worker!
 *
 * You'll need to register this file in your web app and you should
 * disable HTTP caching for this file too.
 * See https://goo.gl/nhQhGp
 *
 * The rest of the code is auto-generated. Please don't update this file
 * directly; instead, make changes to your Workbox build configuration
 * and re-run your build process.
 * See https://goo.gl/2aRDsh
 */

importScripts("https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js");

self.addEventListener('push', function(event) {
  const analyticsPromise = pushReceivedTracking();
  const pushInfoPromise = fetch('/get-more-data')
    .then(function(response) {
      return response.json();
    })
    .then(function(response) {
      const title = response.data.userName + ' says...';
      const message = response.data.message;

      self.registration.showNotification(title, {
        body: message
      });
    });

  const promiseChain = Promise.all([
    analyticsPromise,
    pushInfoPromise
  ]);

  event.waitUntil(promiseChain);
});
/**
 * The workboxSW.precacheAndRoute() method efficiently caches and responds to
 * requests for URLs in the manifest.
 * See https://goo.gl/S9QRab
 */
self.__precacheManifest = [
  {
    "url": "checkout.html",
    "revision": "9c3f69d6504f8109ae88622c487f4c30"
  },
  {
    "url": "favicon.ico",
    "revision": "b802fba5761ac4b0d89b812f4d637f4c"
  },
  {
    "url": "images/about-hero-image.jpg",
    "revision": "8416519ae2b5a1cf9a15b750afaf3994"
  },
  {
    "url": "images/delete.svg",
    "revision": "c3473e39fabe23e47a9971b00e15be29"
  },
  {
    "url": "images/footer-background.png",
    "revision": "8baa656efb23ae4e9274a6deb88a2de2"
  },
  {
    "url": "images/hamburger.svg",
    "revision": "d2cb0dda3e8313b990e8dcf5e25d2d0f"
  },
  {
    "url": "images/header-bg.jpg",
    "revision": "1c38155a29f918a6fc4e4b7d1d45ce69"
  },
  {
    "url": "images/log.png",
    "revision": "2f8040a68be7dc650fe682980911c3a7"
  },
  {
    "url": "images/logo.png",
    "revision": "2f8040a68be7dc650fe682980911c3a7"
  },
  {
    "url": "images/og_image.jpg",
    "revision": "2aa407d02a881716d22daaf4d035adce"
  },
  {
    "url": "images/products/BarrelChair.jpg",
    "revision": "8d89264d1515ef42e72a8550f1bf6b95"
  },
  {
    "url": "images/products/C10.jpg",
    "revision": "ff2c26fd99e5711308eaade646b554e2"
  },
  {
    "url": "images/products/Cl2.jpg",
    "revision": "f66af06555ec2ab57331fa804833459d"
  },
  {
    "url": "images/products/CP03_blue.jpg",
    "revision": "327073b6bdb702024ce6332cef29f586"
  },
  {
    "url": "images/products/CPC_RECYCLED.jpg",
    "revision": "86f6d6874edc03e48543099ad058e138"
  },
  {
    "url": "images/products/CPFS.jpg",
    "revision": "5a9f02005fc429b627350e8db675cb2f"
  },
  {
    "url": "images/products/CPO2_red.jpg",
    "revision": "d7744e1acb43af8dbc74f67fb923fd46"
  },
  {
    "url": "images/products/CPT.jpg",
    "revision": "853b21b5c962e555b4b6eacf89529848"
  },
  {
    "url": "images/products/CS1.jpg",
    "revision": "cffcd8f427eab15d91925fc261853e53"
  },
  {
    "url": "images/products/house.jpg",
    "revision": "a7821b4c4e7ffc6d51caba3f229fd912"
  },
  {
    "url": "images/products/nota1.jpg",
    "revision": "ed39e99df2af96e91e5a14cf1456ffa1"
  },
  {
    "url": "images/products/nota2.jpg",
    "revision": "cfd8f26b842000639da12a6f95b362dc"
  },
  {
    "url": "images/products/nota3.jpg",
    "revision": "74f59e3b8d3940b371ee3a802628d444"
  },
  {
    "url": "images/products/nota4.jpg",
    "revision": "b19c1d127d387983f3d6fc18c61f5caa"
  },
  {
    "url": "images/products/notarizedSign.jpg",
    "revision": "89f1a075775c074b14aefd68841f3ba2"
  },
  {
    "url": "images/products/notary.jpg",
    "revision": "5e37be15e6b64e252bc499a5fd140ffb"
  },
  {
    "url": "images/products/sailletter.jpg",
    "revision": "e09d5744b116051d714c4888fdf652ba"
  },
  {
    "url": "images/products/sheet bulk.jpg",
    "revision": "f6c0e41eb4aedd08e492927485b02985"
  },
  {
    "url": "images/products/tesla.jpg",
    "revision": "9561c9e5135ffb597b5967b71f434e58"
  },
  {
    "url": "images/products/uscis.jpg",
    "revision": "9aa3bde5e8173c44ce0f9b56650a319b"
  },
  {
    "url": "images/products/uscis1.jpg",
    "revision": "286ac9462a6444f4ec7ab61674b9e6e1"
  },
  {
    "url": "images/products/uscis2.jpg",
    "revision": "f6d89558193c7bdaf2c5c1b827e523a9"
  },
  {
    "url": "images/products/wedding.jpg",
    "revision": "88832a6aaa33179491f0ed544c654e72"
  },
  {
    "url": "images/stripe.jpg",
    "revision": "c37cc6ca5a2e214f56894b27a579f19e"
  },
  {
    "url": "images/touch/apple-touch-icon.png",
    "revision": "7326f54bfe6776293f08b34c3a5fde7b"
  },
  {
    "url": "images/touch/chrome-touch-icon-192x192.png",
    "revision": "571f134f59f14a6d298ddd66c015b293"
  },
  {
    "url": "images/touch/icon-128x128.png",
    "revision": "7c46d686765c49b813ac5eb34fabf712"
  },
  {
    "url": "images/touch/ms-touch-icon-144x144-precomposed.png",
    "revision": "452d90b250d6f41a0c8f9db729113ffd"
  },
  {
    "url": "index.html",
    "revision": "cfea94468180c3358f11f7eeafd26fe4"
  },
  {
    "url": "manifest.json",
    "revision": "497175cc23856ee9a7407594cb97a35c"
  },
  {
    "url": "manifest.webapp",
    "revision": "5dc1ecf224aa3b25d7096044911421b2"
  },
  {
    "url": "robots.txt",
    "revision": "6f94032faf83ae58741013c8fee07cb3"
  },
  {
    "url": "scripts/main.min.js",
    "revision": "02e10c6cccbaf297ba69b555a5fdf76f"
  },
  {
    "url": "app.js",
    "revision": "18f1ef5bc03c028af833f73cc744d671"
  },
  {
    "url": "cart-view.js",
    "revision": "d1b75912f02e1fbe2241d0bd246b27f7"
  },
  {
    "url": "cart.js",
    "revision": "47b0b6ac8c975ffdcf32eca057947949"
  },
  {
    "url": "confirmation-view.js",
    "revision": "56d3f0f2c6c712a0d4fdec86c6b0dd15"
  },
  {
    "url": "features.js",
    "revision": "b59273705dd99b9ae3db2af7fa8f2a24"
  },
  {
    "url": "header-controller.js",
    "revision": "0e3d926c86e995499470608f7a7b9082"
  },
  {
    "url": "idb-storage.js",
    "revision": "9c4ddae9d850a3ac0ddf495d326bd7b8"
  },
  {
    "url": "local-storage.js",
    "revision": "e8eaa2149222dd4003c33b1f60ebd3f3"
  },
  {
    "url": "merchant-server.js",
    "revision": "133a4ae98bff363245498c213c494031"
  },
  {
    "url": "payment-api.js",
    "revision": "ca58a30c236a801d52fafee15ce0a543"
  },
  {
    "url": "payment-form.js",
    "revision": "4026f8b36bd3a417c08aea4fd19dce11"
  },
  {
    "url": "product.js",
    "revision": "4e015c4a0840649186973eda228a9157"
  },
  {
    "url": "products.js",
    "revision": "aec637dc378fd46b2280d87ae0f576f1"
  },
  {
    "url": "shop-view.js",
    "revision": "da58d47824337a44f8ee36632256426b"
  },
  {
    "url": "snackbar.js",
    "revision": "b888bd90e1ce1980742c0c5318b5c600"
  },
  {
    "url": "url-tools.js",
    "revision": "bf6311362e5fb7d9da19f9f167ac1c99"
  },
  {
    "url": "view.js",
    "revision": "c572ea083f1a44444975dc38d88e9600"
  },
  {
    "url": "runtime-caching.js",
    "revision": "4f3881ee12be74267853341468418ccb"
  },
  {
    "url": "styles/main.css",
    "revision": "5a6e96affea66a47319e2baf79594ba6"
  }
].concat(self.__precacheManifest || []);




workbox.precaching.precacheAndRoute(self.__precacheManifest, {});


